[package]
name = "entrycgui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.36.1"
egui = "0.36.1"
egui_extras = { version = "0.36", features = ["all_loaders"] }
resvg = "0.48.1"
tiny-skia = "0.12.0"
flate2 = "1"
tar = "0.4"
serde = { workspace = true }
serde_json = { workspace = true }
entrycore = { path = "../entrycore" }
rfd = "0.17.2"
