[package]
name = "entryc"
description = "Rust ↔ Entry .ent compiler"
version = "0.1.0"
edition = "2024"
authors = ["Naekkori"]
license = "MIT"

[dependencies]
zip = { workspace = true }
flate2 = "1"
tar = "0.4"
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
entrycore = { path = "../entrycore" }
